import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Container from "@/components/layout/Container";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of service for fai.events, an AI-curated experience discovery platform.",
};

export default function TermsPage() {
  return (
    <>
      <Header />
      <main className="pt-16">
        <section className="py-16 bg-gradient-to-br from-brand-charcoal to-brand-blue">
          <Container>
            <h1 className="text-3xl sm:text-4xl font-bold text-white">Terms of Service</h1>
            <p className="mt-3 text-white/60">Last updated: April 2026</p>
          </Container>
        </section>

        <section className="py-16 bg-white">
          <Container>
            <div className="max-w-3xl mx-auto prose prose-lg prose-brand-charcoal">
              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">1. Acceptance of Terms</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                By accessing and using fai.events, you agree to these Terms of Service. If you do not agree, please do not use the platform.
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">2. About the Platform</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                fai.events is an AI-powered discovery and curation platform that showcases experiences across Thailand. The platform is created and maintained by Raj Goodman. Content on this site is generated and curated using artificial intelligence (Claude AI by Anthropic).
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">3. Informational Purpose</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                fai.events is an informational platform. We do not sell, book, or facilitate transactions for any experiences listed on the site. When you click through to external websites or booking platforms, you are interacting with third-party services. We are not responsible for the quality, accuracy, or availability of experiences offered by third parties.
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">4. AI-Generated Content</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-4">
                Experience descriptions, ratings, summaries, and recommendations on fai.events are generated by artificial intelligence. While we strive for accuracy:
              </p>
              <ul className="list-disc pl-6 text-brand-charcoal/70 space-y-2 mb-6">
                <li>AI-generated content may contain inaccuracies or outdated information</li>
                <li>Scores and ratings reflect AI evaluation criteria and should not be treated as guarantees of quality</li>
                <li>Prices, availability, and details may change without notice</li>
                <li>We recommend verifying all details directly with experience providers before making any bookings or commitments</li>
              </ul>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">5. Intellectual Property</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                The fai.events platform design, branding, and original content are the property of Raj Goodman. Experience images and descriptions may be sourced from publicly available information and belong to their respective owners. If you believe any content on this site infringes your intellectual property, please contact us through rajgoodman.com.
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">6. External Links</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                fai.events contains links to third-party websites including experience providers, booking platforms, and partner sites. We do not control or endorse these external sites and are not responsible for their content, policies, or practices.
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">7. Limitation of Liability</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                fai.events is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from your use of the platform, reliance on AI-generated content, or interactions with third-party experience providers.
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">8. Workshop Listings</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                Workshops listed on fai.events are provided by independent facilitators. Booking, pricing, scheduling, and delivery of workshops are managed directly by the respective facilitators. fai.events serves as a discovery platform and is not a party to any workshop agreements.
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">9. Changes to Terms</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                We may update these Terms of Service from time to time. Continued use of the platform after changes are posted constitutes acceptance of the updated terms.
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">10. Contact</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                For questions about these Terms of Service, please contact us through{" "}
                <a href="https://rajgoodman.com" target="_blank" rel="noopener noreferrer" className="text-brand-blue hover:underline">
                  rajgoodman.com
                </a>.
              </p>
            </div>
          </Container>
        </section>
      </main>
      <Footer />
    </>
  );
}
