import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Container from "@/components/layout/Container";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy policy for fai.events, an AI-curated experience discovery platform.",
};

export default function PrivacyPage() {
  return (
    <>
      <Header />
      <main className="pt-16">
        <section className="py-16 bg-gradient-to-br from-brand-charcoal to-brand-blue">
          <Container>
            <h1 className="text-3xl sm:text-4xl font-bold text-white">Privacy Policy</h1>
            <p className="mt-3 text-white/60">Last updated: April 2026</p>
          </Container>
        </section>

        <section className="py-16 bg-white">
          <Container>
            <div className="max-w-3xl mx-auto prose prose-lg prose-brand-charcoal">
              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">1. Introduction</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                fai.events (&quot;we&quot;, &quot;our&quot;, or &quot;the platform&quot;) is an AI-powered discovery platform for curated experiences across Thailand. This Privacy Policy explains how we collect, use, and protect information when you visit our website at fai.events.
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">2. Information We Collect</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-4">
                fai.events is primarily an informational platform. We collect minimal data:
              </p>
              <ul className="list-disc pl-6 text-brand-charcoal/70 space-y-2 mb-6">
                <li><strong>Usage Data:</strong> We may collect anonymous analytics data such as pages visited, time spent on the site, browser type, and device information to help improve the platform.</li>
                <li><strong>Cookies:</strong> We use essential cookies to operate the website. We do not use advertising or tracking cookies.</li>
                <li><strong>Contact Information:</strong> If you contact us directly via email or through linked external services, we may collect the information you choose to provide.</li>
              </ul>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">3. How We Use Information</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-4">
                We use collected information to:
              </p>
              <ul className="list-disc pl-6 text-brand-charcoal/70 space-y-2 mb-6">
                <li>Operate and improve the fai.events platform</li>
                <li>Understand how visitors use the site</li>
                <li>Ensure the security and reliability of the platform</li>
              </ul>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">4. Third-Party Links</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                fai.events contains links to external websites, including experience providers, booking platforms, and partner sites such as rajgoodman.com. We are not responsible for the privacy practices of these external sites. We encourage you to review the privacy policies of any third-party site you visit.
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">5. AI-Generated Content</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                Experience descriptions, summaries, and evaluations on this platform are generated by artificial intelligence (Claude AI by Anthropic). While we strive for accuracy, AI-generated content may contain errors or outdated information. We recommend verifying details directly with experience providers before booking.
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">6. Data Security</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                We take reasonable measures to protect any data collected through the platform. However, no method of transmission over the internet is 100% secure.
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">7. Children&apos;s Privacy</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                fai.events is not directed at children under 13. We do not knowingly collect personal information from children.
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">8. Changes to This Policy</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                We may update this Privacy Policy from time to time. Changes will be reflected on this page with an updated date.
              </p>

              <h2 className="text-2xl font-bold text-brand-charcoal mt-8 mb-4">9. Contact</h2>
              <p className="text-brand-charcoal/70 leading-relaxed mb-6">
                If you have questions about this Privacy Policy, please contact us through{" "}
                <a href="https://rajgoodman.com" target="_blank" rel="noopener noreferrer" className="text-brand-blue hover:underline">
                  rajgoodman.com
                </a>.
              </p>
            </div>
          </Container>
        </section>
      </main>
      <Footer />
    </>
  );
}
